## Neural Network Introduction #2

This exercise is adapted from https://www.springboard.com/blog/beginners-guide-neural-network-in-python-scikit-learn-0-18/

We'll use SciKit Learn's built in Breast Cancer Data Set which has several features of tumors with a labeled class indicating whether the tumor was Malignant or Benign. We will try to create a neural network model that can take in these features and attempt to predict malignant or benign labels for tumors it has not seen before. Let's go ahead and start by getting the data!

In [23]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

Check out the dataframe - what are the first few rows of data?

In [24]:
# find out the attributes in the dataset
cancer.data[:3]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [25]:
cancer.target[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [27]:
# find out the total instances and number of features
cancer.data.shape


(569, 30)

In [28]:
cancer.target.shape

(569,)

In [31]:
cancer

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [49]:
# find out the total instances and number of features
# cancer['data'].shape
#cancer.drop(columns=['Unnamed: 32','id'], inplace=True)
#cancer.dropna(inplace=True)
#Y=cancer.pop('diagnosis')

In [50]:
# use describe to find out more about the data
print(cancer)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

**Q:** what can you say about this dataset?

Now, set up the data (x) and labels (y)


In [51]:
X = cancer.data
y = cancer.target

#### Train Test Split
 
Let's split our data into training and testing sets, this is done easily with SciKit Learn's train_test_split function from model_selection:

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


#### Data Preprocessing
 
The neural network may have difficulty converging before the maximum number of iterations allowed if the data is not normalized. Multi-layer Perceptron is sensitive to feature scaling, so it is highly recommended to scale your data. Note that you must apply the same scaling to the test set for meaningful results. There are a lot of different methods for normalization of data, we will use the built-in StandardScaler for standardization.

In [42]:
# Import the StandardScalar library
from sklearn.preprocessing import StandardScaler

# Fit only to the training data
scaler = StandardScaler()
scaled = scaler.fit_transform(X_train)
print(scaled)

[[ 0.35581987 -1.72664707  0.41303118 ...  1.05652305  0.51844283
   0.98925483]
 [-0.37326674  0.50881308 -0.39469992 ... -0.89667412 -0.63236707
  -0.11469617]
 [ 1.4033581  -0.15144941  1.34799923 ...  1.46353548  1.02587412
  -0.03369823]
 ...
 [ 0.02898794 -0.56411347 -0.0829084  ... -1.2463348  -0.67979055
  -1.26509354]
 [-0.05760855  0.09614902 -0.04957475 ...  1.05652305  0.45995387
   1.24414347]
 [-0.5604269   0.30837625 -0.61462066 ... -0.6145405  -0.30672581
  -0.8357478 ]]


In [43]:
# Now apply the transformations to the data:
#completed above



#### Training the model
 
Now it is time to train our model. SciKit Learn makes this incredibly easy, by using estimator objects. In this case we will import our estimator (the Multi-Layer Perceptron Classifier model) from the neural_network library of SciKit-Learn!

In [44]:
from sklearn.neural_network import MLPClassifier



Next we create an instance of the model, there are a lot of parameters you can choose to define and customize here, we will only define the hidden_layer_sizes. For this parameter you pass in a tuple consisting of the number of neurons you want at each layer, where the nth entry in the tuple represents the number of neurons in the nth layer of the MLP model. There are many ways to choose these numbers, but for simplicity we will choose 3 layers with the same number of neurons as there are features in our data set:

In [45]:
# create a Multilayerperceptron classifier and call it mlp

mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)



Now that the model has been made we can fit the training data to our model, remember that this data has already been processed and scaled:

In [46]:
mlp.fit(X_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

**Q:** What do you see in the output? What does it tell you?

#### Predictions and Evaluation
 
Now that we have a model it is time to use it to get predictions! We can do this simply with the predict() method off of our fitted model:

In [48]:
mlp.predict([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])



array([0])

Now we can use SciKit-Learn's built in metrics such as a classification report and confusion matrix to evaluate how well our model performed:

In [56]:
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = mlp.predict(X_test)
accuracy_score(y_test, y_pred)

0.973404255319149

In [72]:
from sklearn.metrics import classification_report
#print(classification_report(y_test, y_pred, target_names=target_names))
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96        67
           1       0.97      0.99      0.98       121

    accuracy                           0.97       188
   macro avg       0.98      0.97      0.97       188
weighted avg       0.97      0.97      0.97       188



In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 63,   4],
       [  1, 120]], dtype=int64)

In [58]:
# The accuracy is good. 

**Q:** what conclusion can you make from the confusion matrix?

#### Weights and biases

The downside however to using a Multi-Layer Preceptron model is how difficult it is to interpret the model itself. The weights and biases won't be easily interpretable in relation to which features are important to the model itself.

To extract the MLP weights and biases after training your model, you use its public attributes coefs_ and intercepts_.

In [65]:
len(mlp.coefs_)


3

In [66]:
len(mlp.coefs_[0])

30

In [69]:
# # Print the coefficient values and interpret it
mlp.coefs_

[array([[-0.10124947,  0.17156567, -0.46044828, -0.16280606, -0.29251361],
        [-0.38120099, -0.26918484, -0.19459229, -0.08246254,  0.03214328],
        [-0.25896771,  0.09208435, -0.52179682,  0.31938287, -0.39135985],
        [-0.20937844, -0.16648076, -0.47800589, -0.28258885, -0.24999546],
        [ 0.24876675,  0.38768367, -0.15490416,  0.15927456,  0.31167951],
        [ 0.32688575, -0.3434896 , -0.38159938, -0.27337192,  0.31313142],
        [-0.33210213, -0.06504075,  0.37977395,  0.02749774,  0.15888918],
        [-0.15254981,  0.15455837,  0.27736463, -0.39888025,  0.20713896],
        [ 0.4042994 ,  0.2053605 , -0.18257212,  0.23957766, -0.32855974],
        [-0.04336837,  0.33828342, -0.17122429, -0.1757282 , -0.30636513],
        [-0.39801679,  0.14814611, -0.23888445, -0.19413281, -0.00697808],
        [-0.37345032,  0.06051654, -0.29796932,  0.07418805,  0.16541547],
        [-0.32854752, -0.07019161,  0.16132523, -0.07095504, -0.37267355],
        [ 0.10239434,  0.

In [68]:
len(mlp.intercepts_[0])

5

In [70]:
# Print the intercepts values and interpret it
mlp.intercepts_

[array([-0.3583876 ,  0.3855916 ,  0.05078735, -0.24559933, -0.20509377]),
 array([-0.9001928 , -0.79617403]),
 array([6.76669813])]

In [ ]:
# Print the intercepts values and interpret it

# I do not understand it. 

**Q:** What do you understand from the two values?

#### Additional optional tasks...

select a few known supervised techniques and compare their performance. Use 10 fold cross validation